### ISSUE TITLE
Plugin not compiling

### ISSUE THREAD

**Issue by staalexa** [FebbanHD123/MLGRush#12]
This src as provided does not compile the de.* folder.

**Comment by FebbanHD123** [comment]
Are you compiling the plugin with maven?

**Comment by staalexa** [comment]
yes, loaded it as it is in inteliJ and does not work. Tried both via artifacts and via maven build. The final file does not contain the main plugin folder.

**Comment by staalexa** [comment]
@FebbanHD123 gibt es schon neue Erkenntnisse?

**Comment by FebbanHD123** [comment]
@amazonal3xa Es liegt wahrscheinlich an deiner IDE nicht am Plugin. Bist du sicher das der src ordner von der IDE richtig erkannt wird? Welche IDE benutzt du überhaupt. Falls du Intellij benutzt, kannst du mal probieren den src ordner als source Folder zu deklarieren.

**Comment by staalexa** [comment]
Ich nutze InteliJ Ultimate, also sollte dein Projekt, was auch in InteliJ gemacht ist direkt gehen. Ich schau nochmal nach.. Oder hast du andere Ideen? Sonst geht alles bei mir, nur dein Ordner nicht.
